language: python
#python:
#- '3.7.0'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
- pip3 install .
script:
- python3 setup.py test
deploy:
  - provider: releases
    skip_cleanup: true
    api-key:
      secure: Q3wwYSZkwXAG1DwgKZrR/vZTGLZlDBfR9O5MoZ+dpmy6EmFozQLRB+qFh+eWh2Y8xYIdXz+6CaJLcM92JU5zJTslWLHyhO7kTOt31fxuZu+HGnR835Try6TlU11948nn2Ramk4nI3lT/G4jO+PdNq23sOPdhV4KDI0nv9Pc9Ywqoyg+4okpSnbJNWn7bdinthA88iMRNxqH88LJ4CM6J/eh0qJUm2xcAOTpw9gIkq188UTCbT71qGUWhWFicvbV1oJ6r+C87Ru/rf+nHJyZ7Dn2y8odBx+MHicUp7XomKP/niM2K9TkX/wOMqopE6XrmAnZ/6W/8cGOoqLWT0oqksktIqlOrUYQAq5UNXee3cHPq6k+Q/CGhbGb9feNEzb3PMPKkD6wict90arhHfpqk0yGP1lCRSwM0eIgegMWgSpFXi2Zc+K/6iucZ21ayVDZf20f7Pe70SEgjB/VJiTgI+BMmOG70a2MYsHUG+rK4fYiSDiO+9ADVNHHNy5r9dL+VLhRxkkcgaIkkZsx/xoE2KUO601EOEfjX55S0C8R/VRNDpxg1VXhu2i19E3G08Xcv+xuz8awst3gvVImVJY9j9GiimMtT0l/pLMjWTeAvMmlraxRaMa36Q96BntThdwRkNCAhsfCTF364egRI+PEWciRcrb0Tpj8/L8p2OUMMqgI=
    name: deeputil-0.2.9
    tag_name: 0.2.9
    on:
        branch: master
        repo: deep-compute/deeputil
    # test pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "MFFlIb6WGojDdGRgvMBBrt9GOgAuR5HkRSHlNFkqGo3dc9hLLEV0aGORRMw/n/3WkGTN8fNL5kd7Pe4ODCMb1wz02wGQYgDTHHQUy/GYCI4rv3GzLjWw9TeMKLrgXYBvDdD/ESxesmD2jdqjyh/kwhCiOznTjKcbklGDZH/ycC0yxsR3P3tSCDCTagWpLGUF90Iyz+pNspWdrPmV9mmfPplVf1HNo6UhuGhxMtTcxZsRRNF6s3dh/NFFJmdf9Z0qCp9JV3N9/zGgp8aqjGeJ1w/2ULq05zDgR/CkKIDVTyh6woo/BSPKj9cK4Azr61qRycughA0riUmjCm+14FTj/32FBfgoh6xSNV+N4atgCJEMfVBLyM/4Yh226vwGtQdpPC1ouendfxbUPwh5fVlrWAOO2GwfrEtFb/MwMeA7J/QHQ0jKQ/zA9KV2qVOvbKHAr3yd0MxCdgHjvbTve6a0wyZbkUDDdPMBDJNOMlRh/e0tNZnjenH80NjmryrITR0DuY8OvHAr3oA6sFGWE/bLzoe4IHe8GDuJCNYN5elz95tc1ZYbtFVaTvctUmdRg9biLJnf1V9sKVxu896PMhdC5ONbTyoMeaCycanx7Oft2KhjKTwi8rWiQvczDFkXKtr2abCMIt7EL/rGR/w8ohaCyWMzqB+Ax5m23NUxC0bB+B0="
    on:
      branch: master
      tags: false
    # pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://upload.pypi.org/legacy/
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "MFFlIb6WGojDdGRgvMBBrt9GOgAuR5HkRSHlNFkqGo3dc9hLLEV0aGORRMw/n/3WkGTN8fNL5kd7Pe4ODCMb1wz02wGQYgDTHHQUy/GYCI4rv3GzLjWw9TeMKLrgXYBvDdD/ESxesmD2jdqjyh/kwhCiOznTjKcbklGDZH/ycC0yxsR3P3tSCDCTagWpLGUF90Iyz+pNspWdrPmV9mmfPplVf1HNo6UhuGhxMtTcxZsRRNF6s3dh/NFFJmdf9Z0qCp9JV3N9/zGgp8aqjGeJ1w/2ULq05zDgR/CkKIDVTyh6woo/BSPKj9cK4Azr61qRycughA0riUmjCm+14FTj/32FBfgoh6xSNV+N4atgCJEMfVBLyM/4Yh226vwGtQdpPC1ouendfxbUPwh5fVlrWAOO2GwfrEtFb/MwMeA7J/QHQ0jKQ/zA9KV2qVOvbKHAr3yd0MxCdgHjvbTve6a0wyZbkUDDdPMBDJNOMlRh/e0tNZnjenH80NjmryrITR0DuY8OvHAr3oA6sFGWE/bLzoe4IHe8GDuJCNYN5elz95tc1ZYbtFVaTvctUmdRg9biLJnf1V9sKVxu896PMhdC5ONbTyoMeaCycanx7Oft2KhjKTwi8rWiQvczDFkXKtr2abCMIt7EL/rGR/w8ohaCyWMzqB+Ax5m23NUxC0bB+B0="
    on:
      branch: master
      # only when there is a release it will update pypi
      tags: true
